//
// Created by charl on 31/10/2023.
//

#ifndef NOESISTESTING_BGFXRENDERDEVICEAPI_HPP
#define NOESISTESTING_BGFXRENDERDEVICEAPI_HPP

#include <NsCore/CompilerSettings.h>

#ifndef NS_RENDER_BGFXRENDERDEVICE_API
	#define NS_RENDER_BGFXRENDERDEVICE_API NS_DLL_IMPORT
#endif

#endif //NOESISTESTING_BGFXRENDERDEVICEAPI_HPP
